[package]
name = "rest"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
database = { path = "../../data/database"}
domain = { path="../../domain" }
api = { path="../../presentation/api" }
anyhow = "1.0.89"
